USE CATALOG purgo_databricks;

-- Databricks SQL script: Comprehensive test data generation for trf_inv_txn table
-- Purpose: Generate diverse test records for trf_inv_txn, covering happy path, edge, error, NULL, and special character scenarios
-- Author: Khanh Trinh
-- Date: 2025-10-08
-- Description: This script creates a CTE with 30 test records for trf_inv_txn, using Databricks native data types and formats. It covers valid, boundary, error, NULL, and special character cases, ensuring schema consistency and deduplication. All transformation logic, lookups, and aggregations are handled in CTEs as per requirements.

-- CTE: Generate comprehensive test data for trf_inv_txn

-- Validation Query: Show all test records for trf_inv_txn

WITH test_trf_inv_txn AS (
  SELECT
    -- Happy path: Valid record
    '1001' AS company_cd,
    'PROD001' AS item_nbr,
    'LOC01' AS location_cd,
    'LOT01' AS lot_nbr,
    'AU01' AS plant_cd,
    'mbd' AS src_sys_cd,
    '1000001-1-2023' AS transaction_id,
    'USD' AS company_currency_cd,
    '1000001' AS document_nbr,
    'GL1001' AS gl_account_nbr,
    '20240101' AS posting_dt_yyyymmdd,
    'EA' AS primary_uom_cd,
    'C001' AS reference_order_company_cd,
    1 AS reference_order_schedule_line_nbr,
    'PO' AS reference_order_type,
    '20240102' AS transaction_dt_yyyymmdd,
    100.0 AS transaction_qty_primary_uom,
    50.0 AS transaction_qty_transaction_uom,
    'Goods Receipt' AS transaction_reason,
    '2024-03-21T10:15:30.000+0000' AS transaction_ts,
    'GR' AS transaction_type_cd,
    'EA' AS transaction_uom,
    12.50 AS unit_cost_company_currency,
    'mbd|AU01' AS plant_key,
    'mbd|PROD001' AS prod_key,
    'mbd|PROD001|AU01' AS prod_plant_key,
    'mbd|AU01|LOC01' AS plant_location_key,
    'mbd|AU01|LOT01' AS plant_lot_key,
    'mbd|PROD001|AU01|LOC01' AS prod_plant_location_key,
    'mbd|PROD001|AU01|LOT01' AS prod_plant_lot_key,
    'mbd|PROD001|AU01|LOT01|LOC01' AS prod_plant_lot_location_key,
    'mbd|GL1001' AS gl_acct_key,
    'mbd|1001' AS co_key,
    'no' AS consumption_usage_flag,
    'no' AS receipt_flag,
    'no' AS scrap_flag,
    'no' AS shipment_flag

  UNION ALL
  -- Edge case: NULLs for optional fields
  SELECT
    NULL AS company_cd,
    'PROD002' AS item_nbr,
    NULL AS location_cd,
    NULL AS lot_nbr,
    NULL AS plant_cd,
    'mbd' AS src_sys_cd,
    '1000002-1-2023' AS transaction_id,
    'EUR' AS company_currency_cd,
    '1000002' AS document_nbr,
    'GL1002' AS gl_account_nbr,
    '20240102' AS posting_dt_yyyymmdd,
    'KG' AS primary_uom_cd,
    NULL AS reference_order_company_cd,
    1 AS reference_order_schedule_line_nbr,
    NULL AS reference_order_type,
    '20240103' AS transaction_dt_yyyymmdd,
    200.0 AS transaction_qty_primary_uom,
    100.0 AS transaction_qty_transaction_uom,
    'Stock Transfer' AS transaction_reason,
    '2024-03-21T11:20:00.000+0000' AS transaction_ts,
    'ST' AS transaction_type_cd,
    'KG' AS transaction_uom,
    8.75 AS unit_cost_company_currency,
    'mbd|NULL' AS plant_key,
    'mbd|PROD002' AS prod_key,
    'mbd|PROD002|NULL' AS prod_plant_key,
    'mbd|NULL|NULL' AS plant_location_key,
    'mbd|NULL|NULL' AS plant_lot_key,
    'mbd|PROD002|NULL|NULL' AS prod_plant_location_key,
    'mbd|PROD002|NULL|NULL' AS prod_plant_lot_key,
    'mbd|PROD002|NULL|NULL|NULL' AS prod_plant_lot_location_key,
    'mbd|GL1002' AS gl_acct_key,
    'mbd|NULL' AS co_key,
    'no' AS consumption_usage_flag,
    'no' AS receipt_flag,
    'no' AS scrap_flag,
    'no' AS shipment_flag

  UNION ALL
  -- Error case: Out-of-range values
  SELECT
    '1002' AS company_cd,
    'PROD003' AS item_nbr,
    'LOC03' AS location_cd,
    'LOT03' AS lot_nbr,
    'RM01' AS plant_cd,
    'mbd' AS src_sys_cd,
    '1000003-1-2023' AS transaction_id,
    'JPY' AS company_currency_cd,
    '1000003' AS document_nbr,
    'GL1003' AS gl_account_nbr,
    '20240103' AS posting_dt_yyyymmdd,
    'BOX' AS primary_uom_cd,
    'C003' AS reference_order_company_cd,
    1 AS reference_order_schedule_line_nbr,
    'WO' AS reference_order_type,
    '20240104' AS transaction_dt_yyyymmdd,
    -9999999999.99 AS transaction_qty_primary_uom,
    9999999999.99 AS transaction_qty_transaction_uom,
    'Scrap' AS transaction_reason,
    '2024-03-21T12:30:00.000+0000' AS transaction_ts,
    'SC' AS transaction_type_cd,
    'BOX' AS transaction_uom,
    0.00 AS unit_cost_company_currency,
    'mbd|RM01' AS plant_key,
    'mbd|PROD003' AS prod_key,
    'mbd|PROD003|RM01' AS prod_plant_key,
    'mbd|RM01|LOC03' AS plant_location_key,
    'mbd|RM01|LOT03' AS plant_lot_key,
    'mbd|PROD003|RM01|LOC03' AS prod_plant_location_key,
    'mbd|PROD003|RM01|LOT03' AS prod_plant_lot_key,
    'mbd|PROD003|RM01|LOT03|LOC03' AS prod_plant_lot_location_key,
    'mbd|GL1003' AS gl_acct_key,
    'mbd|1002' AS co_key,
    'no' AS consumption_usage_flag,
    'no' AS receipt_flag,
    'no' AS scrap_flag,
    'no' AS shipment_flag

  UNION ALL
  -- Error case: Invalid combination (negative quantity with receipt type)
  SELECT
    '1003' AS company_cd,
    'PROD004' AS item_nbr,
    'LOC04' AS location_cd,
    'LOT04' AS lot_nbr,
    'BAS1' AS plant_cd,
    'mbd' AS src_sys_cd,
    '1000004-1-2023' AS transaction_id,
    'GBP' AS company_currency_cd,
    '1000004' AS document_nbr,
    'GL1004' AS gl_account_nbr,
    '20240104' AS posting_dt_yyyymmdd,
    'L' AS primary_uom_cd,
    'C004' AS reference_order_company_cd,
    1 AS reference_order_schedule_line_nbr,
    'SO' AS reference_order_type,
    '20240105' AS transaction_dt_yyyymmdd,
    -50.0 AS transaction_qty_primary_uom,
    -25.0 AS transaction_qty_transaction_uom,
    'Receipt' AS transaction_reason,
    '2024-03-21T13:45:00.000+0000' AS transaction_ts,
    'RC' AS transaction_type_cd,
    'L' AS transaction_uom,
    15.00 AS unit_cost_company_currency,
    'mbd|BAS1' AS plant_key,
    'mbd|PROD004' AS prod_key,
    'mbd|PROD004|BAS1' AS prod_plant_key,
    'mbd|BAS1|LOC04' AS plant_location_key,
    'mbd|BAS1|LOT04' AS plant_lot_key,
    'mbd|PROD004|BAS1|LOC04' AS prod_plant_location_key,
    'mbd|PROD004|BAS1|LOT04' AS prod_plant_lot_key,
    'mbd|PROD004|BAS1|LOT04|LOC04' AS prod_plant_lot_location_key,
    'mbd|GL1004' AS gl_acct_key,
    'mbd|1003' AS co_key,
    'no' AS consumption_usage_flag,
    'no' AS receipt_flag,
    'no' AS scrap_flag,
    'no' AS shipment_flag

  UNION ALL
  -- Happy path: Special characters and multi-byte characters
  SELECT
    '公司1005' AS company_cd,
    '产品005' AS item_nbr,
    '位置05' AS location_cd,
    '批次05' AS lot_nbr,
    '工厂05' AS plant_cd,
    'mbd' AS src_sys_cd,
    '1000005-1-2023' AS transaction_id,
    'CNY' AS company_currency_cd,
    '1000005' AS document_nbr,
    'GL1005' AS gl_account_nbr,
    '20240105' AS posting_dt_yyyymmdd,
    '件' AS primary_uom_cd,
    '公司C005' AS reference_order_company_cd,
    1 AS reference_order_schedule_line_nbr,
    'PO' AS reference_order_type,
    '20240106' AS transaction_dt_yyyymmdd,
    500.0 AS transaction_qty_primary_uom,
    250.0 AS transaction_qty_transaction_uom,
    '入库' AS transaction_reason,
    '2024-03-21T14:55:00.000+0000' AS transaction_ts,
    'GR' AS transaction_type_cd,
    '件' AS transaction_uom,
    20.00 AS unit_cost_company_currency,
    'mbd|工厂05' AS plant_key,
    'mbd|产品005' AS prod_key,
    'mbd|产品005|工厂05' AS prod_plant_key,
    'mbd|工厂05|位置05' AS plant_location_key,
    'mbd|工厂05|批次05' AS plant_lot_key,
    'mbd|产品005|工厂05|位置05' AS prod_plant_location_key,
    'mbd|产品005|工厂05|批次05' AS prod_plant_lot_key,
    'mbd|产品005|工厂05|批次05|位置05' AS prod_plant_lot_location_key,
    'mbd|GL1005' AS gl_acct_key,
    'mbd|公司1005' AS co_key,
    'no' AS consumption_usage_flag,
    'no' AS receipt_flag,
    'no' AS scrap_flag,
    'no' AS shipment_flag

  UNION ALL
  -- Edge case: Empty string for optional fields
  SELECT
    '' AS company_cd,
    'PROD006' AS item_nbr,
    '' AS location_cd,
    '' AS lot_nbr,
    '' AS plant_cd,
    'mbd' AS src_sys_cd,
    '1000006-1-2023' AS transaction_id,
    'AUD' AS company_currency_cd,
    '1000006' AS document_nbr,
    'GL1006' AS gl_account_nbr,
    '20240106' AS posting_dt_yyyymmdd,
    'M' AS primary_uom_cd,
    '' AS reference_order_company_cd,
    1 AS reference_order_schedule_line_nbr,
    '' AS reference_order_type,
    '20240107' AS transaction_dt_yyyymmdd,
    600.0 AS transaction_qty_primary_uom,
    300.0 AS transaction_qty_transaction_uom,
    '' AS transaction_reason,
    '2024-03-21T15:05:00.000+0000' AS transaction_ts,
    'TR' AS transaction_type_cd,
    'M' AS transaction_uom,
    5.00 AS unit_cost_company_currency,
    'mbd|' AS plant_key,
    'mbd|PROD006' AS prod_key,
    'mbd|PROD006|' AS prod_plant_key,
    'mbd||' AS plant_location_key,
    'mbd||' AS plant_lot_key,
    'mbd|PROD006||' AS prod_plant_location_key,
    'mbd|PROD006||' AS prod_plant_lot_key,
    'mbd|PROD006|||' AS prod_plant_lot_location_key,
    'mbd|GL1006' AS gl_acct_key,
    'mbd|' AS co_key,
    'no' AS consumption_usage_flag,
    'no' AS receipt_flag,
    'no' AS scrap_flag,
    'no' AS shipment_flag

  UNION ALL
  -- Error case: Type mismatch (string in numeric field)
  SELECT
    '1007' AS company_cd,
    'PROD007' AS item_nbr,
    'LOC07' AS location_cd,
    'LOT07' AS lot_nbr,
    'RM02' AS plant_cd,
    'mbd' AS src_sys_cd,
    '1000007-1-2023' AS transaction_id,
    'INR' AS company_currency_cd,
    '1000007' AS document_nbr,
    'GL1007' AS gl_account_nbr,
    '20240107' AS posting_dt_yyyymmdd,
    'KG' AS primary_uom_cd,
    'C007' AS reference_order_company_cd,
    1 AS reference_order_schedule_line_nbr,
    'WO' AS reference_order_type,
    '20240108' AS transaction_dt_yyyymmdd,
    CAST('abc' AS DOUBLE) AS transaction_qty_primary_uom, -- Will error in validation
    350.0 AS transaction_qty_transaction_uom,
    'Production' AS transaction_reason,
    '2024-03-21T16:10:00.000+0000' AS transaction_ts,
    'PR' AS transaction_type_cd,
    'KG' AS transaction_uom,
    7.50 AS unit_cost_company_currency,
    'mbd|RM02' AS plant_key,
    'mbd|PROD007' AS prod_key,
    'mbd|PROD007|RM02' AS prod_plant_key,
    'mbd|RM02|LOC07' AS plant_location_key,
    'mbd|RM02|LOT07' AS plant_lot_key,
    'mbd|PROD007|RM02|LOC07' AS prod_plant_location_key,
    'mbd|PROD007|RM02|LOT07' AS prod_plant_lot_key,
    'mbd|PROD007|RM02|LOT07|LOC07' AS prod_plant_lot_location_key,
    'mbd|GL1007' AS gl_acct_key,
    'mbd|1007' AS co_key,
    'no' AS consumption_usage_flag,
    'no' AS receipt_flag,
    'no' AS scrap_flag,
    'no' AS shipment_flag

  UNION ALL
  -- Edge case: Boundary date (exactly 5 years ago)
  SELECT
    '1008' AS company_cd,
    'PROD008' AS item_nbr,
    'LOC08' AS location_cd,
    'LOT08' AS lot_nbr,
    'CA01' AS plant_cd,
    'mbd' AS src_sys_cd,
    '1000008-1-2019' AS transaction_id,
    'CAD' AS company_currency_cd,
    '1000008' AS document_nbr,
    'GL1008' AS gl_account_nbr,
    '20191008' AS posting_dt_yyyymmdd,
    'EA' AS primary_uom_cd,
    'C008' AS reference_order_company_cd,
    1 AS reference_order_schedule_line_nbr,
    'PO' AS reference_order_type,
    '20191009' AS transaction_dt_yyyymmdd,
    800.0 AS transaction_qty_primary_uom,
    400.0 AS transaction_qty_transaction_uom,
    'Boundary Date' AS transaction_reason,
    '2019-10-08T08:00:00.000+0000' AS transaction_ts,
    'GR' AS transaction_type_cd,
    'EA' AS transaction_uom,
    10.00 AS unit_cost_company_currency,
    'mbd|CA01' AS plant_key,
    'mbd|PROD008' AS prod_key,
    'mbd|PROD008|CA01' AS prod_plant_key,
    'mbd|CA01|LOC08' AS plant_location_key,
    'mbd|CA01|LOT08' AS plant_lot_key,
    'mbd|PROD008|CA01|LOC08' AS prod_plant_location_key,
    'mbd|PROD008|CA01|LOT08' AS prod_plant_lot_key,
    'mbd|PROD008|CA01|LOT08|LOC08' AS prod_plant_lot_location_key,
    'mbd|GL1008' AS gl_acct_key,
    'mbd|1008' AS co_key,
    'no' AS consumption_usage_flag,
    'no' AS receipt_flag,
    'no' AS scrap_flag,
    'no' AS shipment_flag

  UNION ALL
  -- Error case: Invalid date format
  SELECT
    '1009' AS company_cd,
    'PROD009' AS item_nbr,
    'LOC09' AS location_cd,
    'LOT09' AS lot_nbr,
    'CA02' AS plant_cd,
    'mbd' AS src_sys_cd,
    '1000009-1-2023' AS transaction_id,
    'USD' AS company_currency_cd,
    '1000009' AS document_nbr,
    'GL1009' AS gl_account_nbr,
    '2023-01-01' AS posting_dt_yyyymmdd, -- Invalid format
    'EA' AS primary_uom_cd,
    'C009' AS reference_order_company_cd,
    1 AS reference_order_schedule_line_nbr,
    'PO' AS reference_order_type,
    '20240110' AS transaction_dt_yyyymmdd,
    900.0 AS transaction_qty_primary_uom,
    450.0 AS transaction_qty_transaction_uom,
    'Invalid Date' AS transaction_reason,
    '2024-03-21T17:20:00.000+0000' AS transaction_ts,
    'GR' AS transaction_type_cd,
    'EA' AS transaction_uom,
    11.00 AS unit_cost_company_currency,
    'mbd|CA02' AS plant_key,
    'mbd|PROD009' AS prod_key,
    'mbd|PROD009|CA02' AS prod_plant_key,
    'mbd|CA02|LOC09' AS plant_location_key,
    'mbd|CA02|LOT09' AS plant_lot_key,
    'mbd|PROD009|CA02|LOC09' AS prod_plant_location_key,
    'mbd|PROD009|CA02|LOT09' AS prod_plant_lot_key,
    'mbd|PROD009|CA02|LOT09|LOC09' AS prod_plant_lot_location_key,
    'mbd|GL1009' AS gl_acct_key,
    'mbd|1009' AS co_key,
    'no' AS consumption_usage_flag,
    'no' AS receipt_flag,
    'no' AS scrap_flag,
    'no' AS shipment_flag

  UNION ALL
  -- Happy path: Deduplication scenario (duplicate composite key)
  SELECT
    '1010' AS company_cd,
    'PROD010' AS item_nbr,
    'LOC10' AS location_cd,
    'LOT10' AS lot_nbr,
    'DAR1' AS plant_cd,
    'mbd' AS src_sys_cd,
    '1000010-1-2023' AS transaction_id,
    'USD' AS company_currency_cd,
    '1000010' AS document_nbr,
    'GL1010' AS gl_account_nbr,
    '20240110' AS posting_dt_yyyymmdd,
    'EA' AS primary_uom_cd,
    'C010' AS reference_order_company_cd,
    1 AS reference_order_schedule_line_nbr,
    'PO' AS reference_order_type,
    '20240111' AS transaction_dt_yyyymmdd,
    1000.0 AS transaction_qty_primary_uom,
    500.0 AS transaction_qty_transaction_uom,
    'Deduplication' AS transaction_reason,
    '2024-03-21T18:30:00.000+0000' AS transaction_ts,
    'GR' AS transaction_type_cd,
    'EA' AS transaction_uom,
    13.00 AS unit_cost_company_currency,
    'mbd|DAR1' AS plant_key,
    'mbd|PROD010' AS prod_key,
    'mbd|PROD010|DAR1' AS prod_plant_key,
    'mbd|DAR1|LOC10' AS plant_location_key,
    'mbd|DAR1|LOT10' AS plant_lot_key,
    'mbd|PROD010|DAR1|LOC10' AS prod_plant_location_key,
    'mbd|PROD010|DAR1|LOT10' AS prod_plant_lot_key,
    'mbd|PROD010|DAR1|LOT10|LOC10' AS prod_plant_lot_location_key,
    'mbd|GL1010' AS gl_acct_key,
    'mbd|1010' AS co_key,
    'no' AS consumption_usage_flag,
    'no' AS receipt_flag,
    'no' AS scrap_flag,
    'no' AS shipment_flag

  UNION ALL
  -- Duplicate record for deduplication test
  SELECT
    '1010' AS company_cd,
    'PROD010' AS item_nbr,
    'LOC10' AS location_cd,
    'LOT10' AS lot_nbr,
    'DAR1' AS plant_cd,
    'mbd' AS src_sys_cd,
    '1000010-1-2023' AS transaction_id,
    'USD' AS company_currency_cd,
    '1000010' AS document_nbr,
    'GL1010' AS gl_account_nbr,
    '20240110' AS posting_dt_yyyymmdd,
    'EA' AS primary_uom_cd,
    'C010' AS reference_order_company_cd,
    1 AS reference_order_schedule_line_nbr,
    'PO' AS reference_order_type,
    '20240111' AS transaction_dt_yyyymmdd,
    1000.0 AS transaction_qty_primary_uom,
    500.0 AS transaction_qty_transaction_uom,
    'Deduplication' AS transaction_reason,
    '2024-03-21T18:30:00.000+0000' AS transaction_ts,
    'GR' AS transaction_type_cd,
    'EA' AS transaction_uom,
    13.00 AS unit_cost_company_currency,
    'mbd|DAR1' AS plant_key,
    'mbd|PROD010' AS prod_key,
    'mbd|PROD010|DAR1' AS prod_plant_key,
    'mbd|DAR1|LOC10' AS plant_location_key,
    'mbd|DAR1|LOT10' AS plant_lot_key,
    'mbd|PROD010|DAR1|LOC10' AS prod_plant_location_key,
    'mbd|PROD010|DAR1|LOT10' AS prod_plant_lot_key,
    'mbd|PROD010|DAR1|LOT10|LOC10' AS prod_plant_lot_location_key,
    'mbd|GL1010' AS gl_acct_key,
    'mbd|1010' AS co_key,
    'no' AS consumption_usage_flag,
    'no' AS receipt_flag,
    'no' AS scrap_flag,
    'no' AS shipment_flag

  UNION ALL
  -- Movement flag mapping: bwart 641
  SELECT
    '1011' AS company_cd,
    'PROD011' AS item_nbr,
    'LOC11' AS location_cd,
    'LOT11' AS lot_nbr,
    'DE20' AS plant_cd,
    'mbd' AS src_sys_cd,
    '1000011-1-2023' AS transaction_id,
    'EUR' AS company_currency_cd,
    '1000011' AS document_nbr,
    'GL1011' AS gl_account_nbr,
    '20240111' AS posting_dt_yyyymmdd,
    'EA' AS primary_uom_cd,
    'C011' AS reference_order_company_cd,
    1 AS reference_order_schedule_line_nbr,
    'PO' AS reference_order_type,
    '20240112' AS transaction_dt_yyyymmdd,
    1100.0 AS transaction_qty_primary_uom,
    550.0 AS transaction_qty_transaction_uom,
    'Movement 641' AS transaction_reason,
    '2024-03-21T19:40:00.000+0000' AS transaction_ts,
    'GR' AS transaction_type_cd,
    'EA' AS transaction_uom,
    14.00 AS unit_cost_company_currency,
    'mbd|DE20' AS plant_key,
    'mbd|PROD011' AS prod_key,
    'mbd|PROD011|DE20' AS prod_plant_key,
    'mbd|DE20|LOC11' AS plant_location_key,
    'mbd|DE20|LOT11' AS plant_lot_key,
    'mbd|PROD011|DE20|LOC11' AS prod_plant_location_key,
    'mbd|PROD011|DE20|LOT11' AS prod_plant_lot_key,
    'mbd|PROD011|DE20|LOT11|LOC11' AS prod_plant_lot_location_key,
    'mbd|GL1011' AS gl_acct_key,
    'mbd|1011' AS co_key,
    'no' AS consumption_usage_flag,
    'no' AS receipt_flag,
    'no' AS scrap_flag,
    'no' AS shipment_flag

  UNION ALL
  -- Movement flag mapping: bwart 642
  SELECT
    '1012' AS company_cd,
    'PROD012' AS item_nbr,
    'LOC12' AS location_cd,
    'LOT12' AS lot_nbr,
    'FR01' AS plant_cd,
    'mbd' AS src_sys_cd,
    '1000012-1-2023' AS transaction_id,
    'EUR' AS company_currency_cd,
    '1000012' AS document_nbr,
    'GL1012' AS gl_account_nbr,
    '20240112' AS posting_dt_yyyymmdd,
    'EA' AS primary_uom_cd,
    'C012' AS reference_order_company_cd,
    1 AS reference_order_schedule_line_nbr,
    'PO' AS reference_order_type,
    '20240113' AS transaction_dt_yyyymmdd,
    1200.0 AS transaction_qty_primary_uom,
    600.0 AS transaction_qty_transaction_uom,
    'Movement 642' AS transaction_reason,
    '2024-03-21T20:50:00.000+0000' AS transaction_ts,
    'GR' AS transaction_type_cd,
    'EA' AS transaction_uom,
    15.00 AS unit_cost_company_currency,
    'mbd|FR01' AS plant_key,
    'mbd|PROD012' AS prod_key,
    'mbd|PROD012|FR01' AS prod_plant_key,
    'mbd|FR01|LOC12' AS plant_location_key,
    'mbd|FR01|LOT12' AS plant_lot_key,
    'mbd|PROD012|FR01|LOC12' AS prod_plant_location_key,
    'mbd|PROD012|FR01|LOT12' AS prod_plant_lot_key,
    'mbd|PROD012|FR01|LOT12|LOC12' AS prod_plant_lot_location_key,
    'mbd|GL1012' AS gl_acct_key,
    'mbd|1012' AS co_key,
    'no' AS consumption_usage_flag,
    'no' AS receipt_flag,
    'no' AS scrap_flag,
    'no' AS shipment_flag

  UNION ALL
  -- Movement flag mapping: bwart 643
  SELECT
    '1013' AS company_cd,
    'PROD013' AS item_nbr,
    'LOC13' AS location_cd,
    'LOT13' AS lot_nbr,
    'IT01' AS plant_cd,
    'mbd' AS src_sys_cd,
    '1000013-1-2023' AS transaction_id,
    'EUR' AS company_currency_cd,
    '1000013' AS document_nbr,
    'GL1013' AS gl_account_nbr,
    '20240113' AS posting_dt_yyyymmdd,
    'EA' AS primary_uom_cd,
    'C013' AS reference_order_company_cd,
    1 AS reference_order_schedule_line_nbr,
    'PO' AS reference_order_type,
    '20240114' AS transaction_dt_yyyymmdd,
    1300.0 AS transaction_qty_primary_uom,
    650.0 AS transaction_qty_transaction_uom,
    'Movement 643' AS transaction_reason,
    '2024-03-21T21:55:00.000+0000' AS transaction_ts,
    'GR' AS transaction_type_cd,
    'EA' AS transaction_uom,
    16.00 AS unit_cost_company_currency,
    'mbd|IT01' AS plant_key,
    'mbd|PROD013' AS prod_key,
    'mbd|PROD013|IT01' AS prod_plant_key,
    'mbd|IT01|LOC13' AS plant_location_key,
    'mbd|IT01|LOT13' AS plant_lot_key,
    'mbd|PROD013|IT01|LOC13' AS prod_plant_location_key,
    'mbd|PROD013|IT01|LOT13' AS prod_plant_lot_key,
    'mbd|PROD013|IT01|LOT13|LOC13' AS prod_plant_lot_location_key,
    'mbd|GL1013' AS gl_acct_key,
    'mbd|1013' AS co_key,
    'no' AS consumption_usage_flag,
    'no' AS receipt_flag,
    'no' AS scrap_flag,
    'no' AS shipment_flag

  UNION ALL
  -- Reference order type mapping: PO
  SELECT
    '1014' AS company_cd,
    'PROD014' AS item_nbr,
    'LOC14' AS location_cd,
    'LOT14' AS lot_nbr,
    'LAN1' AS plant_cd,
    'mbd' AS src_sys_cd,
    '1000014-1-2023' AS transaction_id,
    'USD' AS company_currency_cd,
    '1000014' AS document_nbr,
    'GL1014' AS gl_account_nbr,
    '20240114' AS posting_dt_yyyymmdd,
    'EA' AS primary_uom_cd,
    'C014' AS reference_order_company_cd,
    1 AS reference_order_schedule_line_nbr,
    'EKKO.BSART' AS reference_order_type,
    '20240115' AS transaction_dt_yyyymmdd,
    1400.0 AS transaction_qty_primary_uom,
    700.0 AS transaction_qty_transaction_uom,
    'PO Order' AS transaction_reason,
    '2024-03-21T22:10:00.000+0000' AS transaction_ts,
    'PO' AS transaction_type_cd,
    'EA' AS transaction_uom,
    17.00 AS unit_cost_company_currency,
    'mbd|LAN1' AS plant_key,
    'mbd|PROD014' AS prod_key,
    'mbd|PROD014|LAN1' AS prod_plant_key,
    'mbd|LAN1|LOC14' AS plant_location_key,
    'mbd|LAN1|LOT14' AS plant_lot_key,
    'mbd|PROD014|LAN1|LOC14' AS prod_plant_location_key,
    'mbd|PROD014|LAN1|LOT14' AS prod_plant_lot_key,
    'mbd|PROD014|LAN1|LOT14|LOC14' AS prod_plant_lot_location_key,
    'mbd|GL1014' AS gl_acct_key,
    'mbd|1014' AS co_key,
    'no' AS consumption_usage_flag,
    'no' AS receipt_flag,
    'no' AS scrap_flag,
    'no' AS shipment_flag

  UNION ALL
  -- Reference order type mapping: SO
  SELECT
    '1015' AS company_cd,
    'PROD015' AS item_nbr,
    'LOC15' AS location_cd,
    'LOT15' AS lot_nbr,
    'MAD1' AS plant_cd,
    'mbd' AS src_sys_cd,
    '1000015-1-2023' AS transaction_id,
    'USD' AS company_currency_cd,
    '1000015' AS document_nbr,
    'GL1015' AS gl_account_nbr,
    '20240115' AS posting_dt_yyyymmdd,
    'EA' AS primary_uom_cd,
    'C015' AS reference_order_company_cd,
    1 AS reference_order_schedule_line_nbr,
    'VBAK.AUART' AS reference_order_type,
    '20240116' AS transaction_dt_yyyymmdd,
    1500.0 AS transaction_qty_primary_uom,
    750.0 AS transaction_qty_transaction_uom,
    'SO Order' AS transaction_reason,
    '2024-03-21T23:20:00.000+0000' AS transaction_ts,
    'SO' AS transaction_type_cd,
    'EA' AS transaction_uom,
    18.00 AS unit_cost_company_currency,
    'mbd|MAD1' AS plant_key,
    'mbd|PROD015' AS prod_key,
    'mbd|PROD015|MAD1' AS prod_plant_key,
    'mbd|MAD1|LOC15' AS plant_location_key,
    'mbd|MAD1|LOT15' AS plant_lot_key,
    'mbd|PROD015|MAD1|LOC15' AS prod_plant_location_key,
    'mbd|PROD015|MAD1|LOT15' AS prod_plant_lot_key,
    'mbd|PROD015|MAD1|LOT15|LOC15' AS prod_plant_lot_location_key,
    'mbd|GL1015' AS gl_acct_key,
    'mbd|1015' AS co_key,
    'no' AS consumption_usage_flag,
    'no' AS receipt_flag,
    'no' AS scrap_flag,
    'no' AS shipment_flag

  UNION ALL
  -- Reference order type mapping: WO
  SELECT
    '1016' AS company_cd,
    'PROD016' AS item_nbr,
    'LOC16' AS location_cd,
    'LOT16' AS lot_nbr,
    'MRB1' AS plant_cd,
    'mbd' AS src_sys_cd,
    '1000016-1-2023' AS transaction_id,
    'USD' AS company_currency_cd,
    '1000016' AS document_nbr,
    'GL1016' AS gl_account_nbr,
    '20240116' AS posting_dt_yyyymmdd,
    'EA' AS primary_uom_cd,
    'C016' AS reference_order_company_cd,
    1 AS reference_order_schedule_line_nbr,
    'AUFK.AUART' AS reference_order_type,
    '20240117' AS transaction_dt_yyyymmdd,
    1600.0 AS transaction_qty_primary_uom,
    800.0 AS transaction_qty_transaction_uom,
    'WO Order' AS transaction_reason,
    '2024-03-21T23:55:00.000+0000' AS transaction_ts,
    'WO' AS transaction_type_cd,
    'EA' AS transaction_uom,
    19.00 AS unit_cost_company_currency,
    'mbd|MRB1' AS plant_key,
    'mbd|PROD016' AS prod_key,
    'mbd|PROD016|MRB1' AS prod_plant_key,
    'mbd|MRB1|LOC16' AS plant_location_key,
    'mbd|MRB1|LOT16' AS plant_lot_key,
    'mbd|PROD016|MRB1|LOC16' AS prod_plant_location_key,
    'mbd|PROD016|MRB1|LOT16' AS prod_plant_lot_key,
    'mbd|PROD016|MRB1|LOT16|LOC16' AS prod_plant_lot_location_key,
    'mbd|GL1016' AS gl_acct_key,
    'mbd|1016' AS co_key,
    'no' AS consumption_usage_flag,
    'no' AS receipt_flag,
    'no' AS scrap_flag,
    'no' AS shipment_flag

  UNION ALL
  -- Reference order type mapping: WC
  SELECT
    '1017' AS company_cd,
    'PROD017' AS item_nbr,
    'LOC17' AS location_cd,
    'LOT17' AS lot_nbr,
    'MY01' AS plant_cd,
    'mbd' AS src_sys_cd,
    '1000017-1-2023' AS transaction_id,
    'USD' AS company_currency_cd,
    '1000017' AS document_nbr,
    'GL1017' AS gl_account_nbr,
    '20240117' AS posting_dt_yyyymmdd,
    'EA' AS primary_uom_cd,
    'C017' AS reference_order_company_cd,
    1 AS reference_order_schedule_line_nbr,
    'AUFK.AUART' AS reference_order_type,
    '20240118' AS transaction_dt_yyyymmdd,
    1700.0 AS transaction_qty_primary_uom,
    850.0 AS transaction_qty_transaction_uom,
    'WC Order' AS transaction_reason,
    '2024-03-22T00:10:00.000+0000' AS transaction_ts,
    'WC' AS transaction_type_cd,
    'EA' AS transaction_uom,
    20.00 AS unit_cost_company_currency,
    'mbd|MY01' AS plant_key,
    'mbd|PROD017' AS prod_key,
    'mbd|PROD017|MY01' AS prod_plant_key,
    'mbd|MY01|LOC17' AS plant_location_key,
    'mbd|MY01|LOT17' AS plant_lot_key,
    'mbd|PROD017|MY01|LOC17' AS prod_plant_location_key,
    'mbd|PROD017|MY01|LOT17' AS prod_plant_lot_key,
    'mbd|PROD017|MY01|LOT17|LOC17' AS prod_plant_lot_location_key,
    'mbd|GL1017' AS gl_acct_key,
    'mbd|1017' AS co_key,
    'no' AS consumption_usage_flag,
    'no' AS receipt_flag,
    'no' AS scrap_flag,
    'no' AS shipment_flag

  UNION ALL
  -- Reference order type mapping: OTHER
  SELECT
    '1018' AS company_cd,
    'PROD018' AS item_nbr,
    'LOC18' AS location_cd,
    'LOT18' AS lot_nbr,
    'NDHL' AS plant_cd,
    'mbd' AS src_sys_cd,
    '1000018-1-2023' AS transaction_id,
    'USD' AS company_currency_cd,
    '1000018' AS document_nbr,
    'GL1018' AS gl_account_nbr,
    '20240118' AS posting_dt_yyyymmdd,
    'EA' AS primary_uom_cd,
    'C018' AS reference_order_company_cd,
    1 AS reference_order_schedule_line_nbr,
    'none' AS reference_order_type,
    '20240119' AS transaction_dt_yyyymmdd,
    1800.0 AS transaction_qty_primary_uom,
    900.0 AS transaction_qty_transaction_uom,
    'Other Order' AS transaction_reason,
    '2024-03-22T01:20:00.000+0000' AS transaction_ts,
    'OT' AS transaction_type_cd,
    'EA' AS transaction_uom,
    21.00 AS unit_cost_company_currency,
    'mbd|NDHL' AS plant_key,
    'mbd|PROD018' AS prod_key,
    'mbd|PROD018|NDHL' AS prod_plant_key,
    'mbd|NDHL|LOC18' AS plant_location_key,
    'mbd|NDHL|LOT18' AS plant_lot_key,
    'mbd|PROD018|NDHL|LOC18' AS prod_plant_location_key,
    'mbd|PROD018|NDHL|LOT18' AS prod_plant_lot_key,
    'mbd|PROD018|NDHL|LOT18|LOC18' AS prod_plant_lot_location_key,
    'mbd|GL1018' AS gl_acct_key,
    'mbd|1018' AS co_key,
    'no' AS consumption_usage_flag,
    'no' AS receipt_flag,
    'no' AS scrap_flag,
    'no' AS shipment_flag

  UNION ALL
  -- Aggregation logic: Multiple records for same composite key, sum qty
  SELECT
    '1019' AS company_cd,
    'PROD019' AS item_nbr,
    'LOC19' AS location_cd,
    'LOT19' AS lot_nbr,
    'NOMB' AS plant_cd,
    'mbd' AS src_sys_cd,
    '1000019-1-2023' AS transaction_id,
    'USD' AS company_currency_cd,
    '1000019' AS document_nbr,
    'GL1019' AS gl_account_nbr,
    '20240119' AS posting_dt_yyyymmdd,
    'EA' AS primary_uom_cd,
    'C019' AS reference_order_company_cd,
    1 AS reference_order_schedule_line_nbr,
    'PO' AS reference_order_type,
    '20240120' AS transaction_dt_yyyymmdd,
    1900.0 AS transaction_qty_primary_uom,
    950.0 AS transaction_qty_transaction_uom,
    'Aggregate Qty' AS transaction_reason,
    '2024-03-22T02:30:00.000+0000' AS transaction_ts,
    'AG' AS transaction_type_cd,
    'EA' AS transaction_uom,
    22.00 AS unit_cost_company_currency,
    'mbd|NOMB' AS plant_key,
    'mbd|PROD019' AS prod_key,
    'mbd|PROD019|NOMB' AS prod_plant_key,
    'mbd|NOMB|LOC19' AS plant_location_key,
    'mbd|NOMB|LOT19' AS plant_lot_key,
    'mbd|PROD019|NOMB|LOC19' AS prod_plant_location_key,
    'mbd|PROD019|NOMB|LOT19' AS prod_plant_lot_key,
    'mbd|PROD019|NOMB|LOT19|LOC19' AS prod_plant_lot_location_key,
    'mbd|GL1019' AS gl_acct_key,
    'mbd|1019' AS co_key,
    'no' AS consumption_usage_flag,
    'no' AS receipt_flag,
    'no' AS scrap_flag,
    'no' AS shipment_flag

  UNION ALL
  -- Aggregation logic: Second record for same composite key, sum qty
  SELECT
    '1019' AS company_cd,
    'PROD019' AS item_nbr,
    'LOC19' AS location_cd,
    'LOT19' AS lot_nbr,
    'NOMB' AS plant_cd,
    'mbd' AS src_sys_cd,
    '1000019-1-2023' AS transaction_id,
    'USD' AS company_currency_cd,
    '1000019' AS document_nbr,
    'GL1019' AS gl_account_nbr,
    '20240119' AS posting_dt_yyyymmdd,
    'EA' AS primary_uom_cd,
    'C019' AS reference_order_company_cd,
    1 AS reference_order_schedule_line_nbr,
    'PO' AS reference_order_type,
    '20240120' AS transaction_dt_yyyymmdd,
    100.0 AS transaction_qty_primary_uom,
    50.0 AS transaction_qty_transaction_uom,
    'Aggregate Qty' AS transaction_reason,
    '2024-03-22T02:30:00.000+0000' AS transaction_ts,
    'AG' AS transaction_type_cd,
    'EA' AS transaction_uom,
    22.00 AS unit_cost_company_currency,
    'mbd|NOMB' AS plant_key,
    'mbd|PROD019' AS prod_key,
    'mbd|PROD019|NOMB' AS prod_plant_key,
    'mbd|NOMB|LOC19' AS plant_location_key,
    'mbd|NOMB|LOT19' AS plant_lot_key,
    'mbd|PROD019|NOMB|LOC19' AS prod_plant_location_key,
    'mbd|PROD019|NOMB|LOT19' AS prod_plant_lot_key,
    'mbd|PROD019|NOMB|LOT19|LOC19' AS prod_plant_lot_location_key,
    'mbd|GL1019' AS gl_acct_key,
    'mbd|1019' AS co_key,
    'no' AS consumption_usage_flag,
    'no' AS receipt_flag,
    'no' AS scrap_flag,
    'no' AS shipment_flag

  UNION ALL
  -- Filter logic: budat older than 5 years (excluded)
  SELECT
    '1020' AS company_cd,
    'PROD020' AS item_nbr,
    'LOC20' AS location_cd,
    'LOT20' AS lot_nbr,
    'NO01' AS plant_cd,
    'mbd' AS src_sys_cd,
    '1000020-1-2010' AS transaction_id,
    'USD' AS company_currency_cd,
    '1000020' AS document_nbr,
    'GL1020' AS gl_account_nbr,
    '20100101' AS posting_dt_yyyymmdd,
    'EA' AS primary_uom_cd,
    'C020' AS reference_order_company_cd,
    1 AS reference_order_schedule_line_nbr,
    'PO' AS reference_order_type,
    '20100102' AS transaction_dt_yyyymmdd,
    2000.0 AS transaction_qty_primary_uom,
    1000.0 AS transaction_qty_transaction_uom,
    'Old Date' AS transaction_reason,
    '2010-01-01T01:00:00.000+0000' AS transaction_ts,
    'GR' AS transaction_type_cd,
    'EA' AS transaction_uom,
    23.00 AS unit_cost_company_currency,
    'mbd|NO01' AS plant_key,
    'mbd|PROD020' AS prod_key,
    'mbd|PROD020|NO01' AS prod_plant_key,
    'mbd|NO01|LOC20' AS plant_location_key,
    'mbd|NO01|LOT20' AS plant_lot_key,
    'mbd|PROD020|NO01|LOC20' AS prod_plant_location_key,
    'mbd|PROD020|NO01|LOT20' AS prod_plant_lot_key,
    'mbd|PROD020|NO01|LOT20|LOC20' AS prod_plant_lot_location_key,
    'mbd|GL1020' AS gl_acct_key,
    'mbd|1020' AS co_key,
    'no' AS consumption_usage_flag,
    'no' AS receipt_flag,
    'no' AS scrap_flag,
    'no' AS shipment_flag

  UNION ALL
  -- Filter logic: MBEW.BWTAR not blank (excluded)
  SELECT
    '1021' AS company_cd,
    'PROD021' AS item_nbr,
    'LOC21' AS location_cd,
    'LOT21' AS lot_nbr,
    'PER1' AS plant_cd,
    'mbd' AS src_sys_cd,
    '1000021-1-2023' AS transaction_id,
    'USD' AS company_currency_cd,
    '1000021' AS document_nbr,
    'GL1021' AS gl_account_nbr,
    '20240121' AS posting_dt_yyyymmdd,
    'EA' AS primary_uom_cd,
    'C021' AS reference_order_company_cd,
    1 AS reference_order_schedule_line_nbr,
    'PO' AS reference_order_type,
    '20240122' AS transaction_dt_yyyymmdd,
    2100.0 AS transaction_qty_primary_uom,
    1050.0 AS transaction_qty_transaction_uom,
    'Non-blank BWTAR' AS transaction_reason,
    '2024-03-22T03:40:00.000+0000' AS transaction_ts,
    'GR' AS transaction_type_cd,
    'EA' AS transaction_uom,
    24.00 AS unit_cost_company_currency,
    'mbd|PER1' AS plant_key,
    'mbd|PROD021' AS prod_key,
    'mbd|PROD021|PER1' AS prod_plant_key,
    'mbd|PER1|LOC21' AS plant_location_key,
    'mbd|PER1|LOT21' AS plant_lot_key,
    'mbd|PROD021|PER1|LOC21' AS prod_plant_location_key,
    'mbd|PROD021|PER1|LOT21' AS prod_plant_lot_key,
    'mbd|PROD021|PER1|LOT21|LOC21' AS prod_plant_lot_location_key,
    'mbd|GL1021' AS gl_acct_key,
    'mbd|1021' AS co_key,
    'no' AS consumption_usage_flag,
    'no' AS receipt_flag,
    'no' AS scrap_flag,
    'no' AS shipment_flag

  UNION ALL
  -- Filter logic: t156t.spras != 'E' (excluded)
  SELECT
    '1022' AS company_cd,
    'PROD022' AS item_nbr,
    'LOC22' AS location_cd,
    'LOT22' AS lot_nbr,
    'PER2' AS plant_cd,
    'mbd' AS src_sys_cd,
    '1000022-1-2023' AS transaction_id,
    'USD' AS company_currency_cd,
    '1000022' AS document_nbr,
    'GL1022' AS gl_account_nbr,
    '20240122' AS posting_dt_yyyymmdd,
    'EA' AS primary_uom_cd,
    'C022' AS reference_order_company_cd,
    1 AS reference_order_schedule_line_nbr,
    'PO' AS reference_order_type,
    '20240123' AS transaction_dt_yyyymmdd,
    2200.0 AS transaction_qty_primary_uom,
    1100.0 AS transaction_qty_transaction_uom,
    'Non-E Spras' AS transaction_reason,
    '2024-03-22T04:50:00.000+0000' AS transaction_ts,
    'GR' AS transaction_type_cd,
    'EA' AS transaction_uom,
    25.00 AS unit_cost_company_currency,
    'mbd|PER2' AS plant_key,
    'mbd|PROD022' AS prod_key,
    'mbd|PROD022|PER2' AS prod_plant_key,
    'mbd|PER2|LOC22' AS plant_location_key,
    'mbd|PER2|LOT22' AS plant_lot_key,
    'mbd|PROD022|PER2|LOC22' AS prod_plant_location_key,
    'mbd|PROD022|PER2|LOT22' AS prod_plant_lot_key,
    'mbd|PROD022|PER2|LOT22|LOC22' AS prod_plant_lot_location_key,
    'mbd|GL1022' AS gl_acct_key,
    'mbd|1022' AS co_key,
    'no' AS consumption_usage_flag,
    'no' AS receipt_flag,
    'no' AS scrap_flag,
    'no' AS shipment_flag

  UNION ALL
  -- Special characters: Emoji in string fields
  SELECT
    '💼1023' AS company_cd,
    '🧪PROD023' AS item_nbr,
    '📦LOC23' AS location_cd,
    '🔢LOT23' AS lot_nbr,
    '🏭PLANT23' AS plant_cd,
    'mbd' AS src_sys_cd,
    '1000023-1-2023' AS transaction_id,
    'USD' AS company_currency_cd,
    '1000023' AS document_nbr,
    'GL1023' AS gl_account_nbr,
    '20240123' AS posting_dt_yyyymmdd,
    'EA' AS primary_uom_cd,
    'C023' AS reference_order_company_cd,
    1 AS reference_order_schedule_line_nbr,
    'PO' AS reference_order_type,
    '20240124' AS transaction_dt_yyyymmdd,
    2300.0 AS transaction_qty_primary_uom,
    1150.0 AS transaction_qty_transaction_uom,
    'Emoji 🚚' AS transaction_reason,
    '2024-03-22T05:55:00.000+0000' AS transaction_ts,
    'GR' AS transaction_type_cd,
    'EA' AS transaction_uom,
    26.00 AS unit_cost_company_currency,
    'mbd|🏭PLANT23' AS plant_key,
    'mbd|🧪PROD023' AS prod_key,
    'mbd|🧪PROD023|🏭PLANT23' AS prod_plant_key,
    'mbd|🏭PLANT23|📦LOC23' AS plant_location_key,
    'mbd|🏭PLANT23|🔢LOT23' AS plant_lot_key,
    'mbd|🧪PROD023|🏭PLANT23|📦LOC23' AS prod_plant_location_key,
    'mbd|🧪PROD023|🏭PLANT23|🔢LOT23' AS prod_plant_lot_key,
    'mbd|🧪PROD023|🏭PLANT23|🔢LOT23|📦LOC23' AS prod_plant_lot_location_key,
    'mbd|GL1023' AS gl_acct_key,
    'mbd|💼1023' AS co_key,
    'no' AS consumption_usage_flag,
    'no' AS receipt_flag,
    'no' AS scrap_flag,
    'no' AS shipment_flag

  UNION ALL
  -- Happy path: Valid record with all fields populated
  SELECT
    '1024' AS company_cd,
    'PROD024' AS item_nbr,
    'LOC24' AS location_cd,
    'LOT24' AS lot_nbr,
    'RM03' AS plant_cd,
    'mbd' AS src_sys_cd,
    '1000024-1-2023' AS transaction_id,
    'USD' AS company_currency_cd,
    '1000024' AS document_nbr,
    'GL1024' AS gl_account_nbr,
    '20240124' AS posting_dt_yyyymmdd,
    'EA' AS primary_uom_cd,
    'C024' AS reference_order_company_cd,
    1 AS reference_order_schedule_line_nbr,
    'PO' AS reference_order_type,
    '20240125' AS transaction_dt_yyyymmdd,
    2400.0 AS transaction_qty_primary_uom,
    1200.0 AS transaction_qty_transaction_uom,
    'Valid Record' AS transaction_reason,
    '2024-03-22T06:10:00.000+0000' AS transaction_ts,
    'GR' AS transaction_type_cd,
    'EA' AS transaction_uom,
    27.00 AS unit_cost_company_currency,
    'mbd|RM03' AS plant_key,
    'mbd|PROD024' AS prod_key,
    'mbd|PROD024|RM03' AS prod_plant_key,
    'mbd|RM03|LOC24' AS plant_location_key,
    'mbd|RM03|LOT24' AS plant_lot_key,
    'mbd|PROD024|RM03|LOC24' AS prod_plant_location_key,
    'mbd|PROD024|RM03|LOT24' AS prod_plant_lot_key,
    'mbd|PROD024|RM03|LOT24|LOC24' AS prod_plant_lot_location_key,
    'mbd|GL1024' AS gl_acct_key,
    'mbd|1024' AS co_key,
    'no' AS consumption_usage_flag,
    'no' AS receipt_flag,
    'no' AS scrap_flag,
    'no' AS shipment_flag

  UNION ALL
  -- Edge case: All fields NULL except required composite key
  SELECT
    NULL AS company_cd,
    NULL AS item_nbr,
    NULL AS location_cd,
    NULL AS lot_nbr,
    NULL AS plant_cd,
    'mbd' AS src_sys_cd,
    '1000025-1-2023' AS transaction_id,
    NULL AS company_currency_cd,
    NULL AS document_nbr,
    NULL AS gl_account_nbr,
    NULL AS posting_dt_yyyymmdd,
    NULL AS primary_uom_cd,
    NULL AS reference_order_company_cd,
    1 AS reference_order_schedule_line_nbr,
    NULL AS reference_order_type,
    NULL AS transaction_dt_yyyymmdd,
    NULL AS transaction_qty_primary_uom,
    NULL AS transaction_qty_transaction_uom,
    NULL AS transaction_reason,
    NULL AS transaction_ts,
    NULL AS transaction_type_cd,
    NULL AS transaction_uom,
    NULL AS unit_cost_company_currency,
    'mbd|NULL' AS plant_key,
    'mbd|NULL' AS prod_key,
    'mbd|NULL|NULL' AS prod_plant_key,
    'mbd|NULL|NULL' AS plant_location_key,
    'mbd|NULL|NULL' AS plant_lot_key,
    'mbd|NULL|NULL|NULL' AS prod_plant_location_key,
    'mbd|NULL|NULL|NULL' AS prod_plant_lot_key,
    'mbd|NULL|NULL|NULL|NULL' AS prod_plant_lot_location_key,
    'mbd|NULL' AS gl_acct_key,
    'mbd|NULL' AS co_key,
    'no' AS consumption_usage_flag,
    'no' AS receipt_flag,
    'no' AS scrap_flag,
    'no' AS shipment_flag

  UNION ALL
  -- Happy path: Valid record with special currency
  SELECT
    '1026' AS company_cd,
    'PROD026' AS item_nbr,
    'LOC26' AS location_cd,
    'LOT26' AS lot_nbr,
    'RM04' AS plant_cd,
    'mbd' AS src_sys_cd,
    '1000026-1-2023' AS transaction_id,
    'CHF' AS company_currency_cd,
    '1000026' AS document_nbr,
    'GL1026' AS gl_account_nbr,
    '20240126' AS posting_dt_yyyymmdd,
    'EA' AS primary_uom_cd,
    'C026' AS reference_order_company_cd,
    1 AS reference_order_schedule_line_nbr,
    'PO' AS reference_order_type,
    '20240127' AS transaction_dt_yyyymmdd,
    2600.0 AS transaction_qty_primary_uom,
    1300.0 AS transaction_qty_transaction_uom,
    'Swiss Franc' AS transaction_reason,
    '2024-03-22T07:20:00.000+0000' AS transaction_ts,
    'GR' AS transaction_type_cd,
    'EA' AS transaction_uom,
    28.00 AS unit_cost_company_currency,
    'mbd|RM04' AS plant_key,
    'mbd|PROD026' AS prod_key,
    'mbd|PROD026|RM04' AS prod_plant_key,
    'mbd|RM04|LOC26' AS plant_location_key,
    'mbd|RM04|LOT26' AS plant_lot_key,
    'mbd|PROD026|RM04|LOC26' AS prod_plant_location_key,
    'mbd|PROD026|RM04|LOT26' AS prod_plant_lot_key,
    'mbd|PROD026|RM04|LOT26|LOC26' AS prod_plant_lot_location_key,
    'mbd|GL1026' AS gl_acct_key,
    'mbd|1026' AS co_key,
    'no' AS consumption_usage_flag,
    'no' AS receipt_flag,
    'no' AS scrap_flag,
    'no' AS shipment_flag

  UNION ALL
  -- Happy path: Valid record with decimal unit cost
  SELECT
    '1027' AS company_cd,
    'PROD027' AS item_nbr,
    'LOC27' AS location_cd,
    'LOT27' AS lot_nbr,
    'RM05' AS plant_cd,
    'mbd' AS src_sys_cd,
    '1000027-1-2023' AS transaction_id,
    'USD' AS company_currency_cd,
    '1000027' AS document_nbr,
    'GL1027' AS gl_account_nbr,
    '20240127' AS posting_dt_yyyymmdd,
    'EA' AS primary_uom_cd,
    'C027' AS reference_order_company_cd,
    1 AS reference_order_schedule_line_nbr,
    'PO' AS reference_order_type,
    '20240128' AS transaction_dt_yyyymmdd,
    2700.0 AS transaction_qty_primary_uom,
    1350.0 AS transaction_qty_transaction_uom,
    'Decimal Cost' AS transaction_reason,
    '2024-03-22T08:30:00.000+0000' AS transaction_ts,
    'GR' AS transaction_type_cd,
    'EA' AS transaction_uom,
    29.99 AS unit_cost_company_currency,
    'mbd|RM05' AS plant_key,
    'mbd|PROD027' AS prod_key,
    'mbd|PROD027|RM05' AS prod_plant_key,
    'mbd|RM05|LOC27' AS plant_location_key,
    'mbd|RM05|LOT27' AS plant_lot_key,
    'mbd|PROD027|RM05|LOC27' AS prod_plant_location_key,
    'mbd|PROD027|RM05|LOT27' AS prod_plant_lot_key,
    'mbd|PROD027|RM05|LOT27|LOC27' AS prod_plant_lot_location_key,
    'mbd|GL1027' AS gl_acct_key,
    'mbd|1027' AS co_key,
    'no' AS consumption_usage_flag,
    'no' AS receipt_flag,
    'no' AS scrap_flag,
    'no' AS shipment_flag

  UNION ALL
  -- Happy path: Valid record with large quantity
  SELECT
    '1028' AS company_cd,
    'PROD028' AS item_nbr,
    'LOC28' AS location_cd,
    'LOT28' AS lot_nbr,
    'RM06' AS plant_cd,
    'mbd' AS src_sys_cd,
    '1000028-1-2023' AS transaction_id,
    'USD' AS company_currency_cd,
    '1000028' AS document_nbr,
    'GL1028' AS gl_account_nbr,
    '20240128' AS posting_dt_yyyymmdd,
    'EA' AS primary_uom_cd,
    'C028' AS reference_order_company_cd,
    1 AS reference_order_schedule_line_nbr,
    'PO' AS reference_order_type,
    '20240129' AS transaction_dt_yyyymmdd,
    99999999.99 AS transaction_qty_primary_uom,
    99999999.99 AS transaction_qty_transaction_uom,
    'Large Qty' AS transaction_reason,
    '2024-03-22T09:40:00.000+0000' AS transaction_ts,
    'GR' AS transaction_type_cd,
    'EA' AS transaction_uom,
    30.00 AS unit_cost_company_currency,
    'mbd|RM06' AS plant_key,
    'mbd|PROD028' AS prod_key,
    'mbd|PROD028|RM06' AS prod_plant_key,
    'mbd|RM06|LOC28' AS plant_location_key,
    'mbd|RM06|LOT28' AS plant_lot_key,
    'mbd|PROD028|RM06|LOC28' AS prod_plant_location_key,
    'mbd|PROD028|RM06|LOT28' AS prod_plant_lot_key,
    'mbd|PROD028|RM06|LOT28|LOC28' AS prod_plant_lot_location_key,
    'mbd|GL1028' AS gl_acct_key,
    'mbd|1028' AS co_key,
    'no' AS consumption_usage_flag,
    'no' AS receipt_flag,
    'no' AS scrap_flag,
    'no' AS shipment_flag

  UNION ALL
  -- Happy path: Valid record with zero quantity
  SELECT
    '1029' AS company_cd,
    'PROD029' AS item_nbr,
    'LOC29' AS location_cd,
    'LOT29' AS lot_nbr,
    'RM07' AS plant_cd,
    'mbd' AS src_sys_cd,
    '1000029-1-2023' AS transaction_id,
    'USD' AS company_currency_cd,
    '1000029' AS document_nbr,
    'GL1029' AS gl_account_nbr,
    '20240129' AS posting_dt_yyyymmdd,
    'EA' AS primary_uom_cd,
    'C029' AS reference_order_company_cd,
    1 AS reference_order_schedule_line_nbr,
    'PO' AS reference_order_type,
    '20240130' AS transaction_dt_yyyymmdd,
    0.0 AS transaction_qty_primary_uom,
    0.0 AS transaction_qty_transaction_uom,
    'Zero Qty' AS transaction_reason,
    '2024-03-22T10:50:00.000+0000' AS transaction_ts,
    'GR' AS transaction_type_cd,
    'EA' AS transaction_uom,
    31.00 AS unit_cost_company_currency,
    'mbd|RM07' AS plant_key,
    'mbd|PROD029' AS prod_key,
    'mbd|PROD029|RM07' AS prod_plant_key,
    'mbd|RM07|LOC29' AS plant_location_key,
    'mbd|RM07|LOT29' AS plant_lot_key,
    'mbd|PROD029|RM07|LOC29' AS prod_plant_location_key,
    'mbd|PROD029|RM07|LOT29' AS prod_plant_lot_key,
    'mbd|PROD029|RM07|LOT29|LOC29' AS prod_plant_lot_location_key,
    'mbd|GL1029' AS gl_acct_key,
    'mbd|1029' AS co_key,
    'no' AS consumption_usage_flag,
    'no' AS receipt_flag,
    'no' AS scrap_flag,
    'no' AS shipment_flag

  UNION ALL
  -- Happy path: Valid record with negative quantity
  SELECT
    '1030' AS company_cd,
    'PROD030' AS item_nbr,
    'LOC30' AS location_cd,
    'LOT30' AS lot_nbr,
    'RM08' AS plant_cd,
    'mbd' AS src_sys_cd,
    '1000030-1-2023' AS transaction_id,
    'USD' AS company_currency_cd,
    '1000030' AS document_nbr,
    'GL1030' AS gl_account_nbr,
    '20240130' AS posting_dt_yyyymmdd,
    'EA' AS primary_uom_cd,
    'C030' AS reference_order_company_cd,
    1 AS reference_order_schedule_line_nbr,
    'PO' AS reference_order_type,
    '20240131' AS transaction_dt_yyyymmdd,
    -100.0 AS transaction_qty_primary_uom,
    -50.0 AS transaction_qty_transaction_uom,
    'Negative Qty' AS transaction_reason,
    '2024-03-22T11:55:00.000+0000' AS transaction_ts,
    'GR' AS transaction_type_cd,
    'EA' AS transaction_uom,
    32.00 AS unit_cost_company_currency,
    'mbd|RM08' AS plant_key,
    'mbd|PROD030' AS prod_key,
    'mbd|PROD030|RM08' AS prod_plant_key,
    'mbd|RM08|LOC30' AS plant_location_key,
    'mbd|RM08|LOT30' AS plant_lot_key,
    'mbd|PROD030|RM08|LOC30' AS prod_plant_location_key,
    'mbd|PROD030|RM08|LOT30' AS prod_plant_lot_key,
    'mbd|PROD030|RM08|LOT30|LOC30' AS prod_plant_lot_location_key,
    'mbd|GL1030' AS gl_acct_key,
    'mbd|1030' AS co_key,
    'no' AS consumption_usage_flag,
    'no' AS receipt_flag,
    'no' AS scrap_flag,
    'no' AS shipment_flag
)

SELECT * FROM test_trf_inv_txn
;
